plugins {
    id 'fabric-loom' version '1.14.10'
    id 'com.modrinth.minotaur' version '2.+'
    id 'maven-publish'
}

var build_num = providers.environmentVariable("GITHUB_RUN_NUMBER")
        .filter { !it.isEmpty() }
        .map { "-build.$it" }
        .orElse(() -> "-local")
        .getOrElse(() -> "")

version = "$mod_version+mc$minecraft_version$build_num"
group = maven_group

base {
    archivesName = archives_base_name
}


fabricApi {
    configureDataGeneration {
        client = true
    }
}

repositories {
    maven {
        name = "Composer Maven"
        url = "https://dl.cloudsmith.io/public/project-codex/composer/maven/"
    }

    maven {
        name "Constructive"
        url "https://dl.cloudsmith.io/public/lilbrocodes/constructive/maven/"
    }

    maven {
        name = "Cardinal Components"
        url = "https://maven.ladysnake.org/releases"
    }
    maven {
        name "Fuzzy Hamsters"
        url "https://maven.fzzyhmstrs.me/"
    }
}

dependencies {
    minecraft "com.mojang:minecraft:$minecraft_version"
    mappings "net.fabricmc:yarn:$yarn_mappings:v2"
    modImplementation "net.fabricmc:fabric-loader:$loader_version"

    modImplementation "net.fabricmc.fabric-api:fabric-api:$fabric_version"
    modImplementation "com.codex:composer:$composer_version+mc$minecraft_version"

    modRuntimeOnly "dev.onyxstudios.cardinal-components-api:cardinal-components-api:5.2.3"
}

processResources {
    inputs.property "version", version
    inputs.property "minecraft_version", minecraft_version
    inputs.property "loader_version", loader_version
    filteringCharset "UTF-8"

    filesMatching("fabric.mod.json") {
        expand "version": version,
                "minecraft_version": minecraft_version,
                "loader_version": loader_version
    }
}

def targetJavaVersion = 17
tasks.withType(JavaCompile).configureEach {
    it.options.encoding = "UTF-8"
    if (targetJavaVersion >= 10 || JavaVersion.current().isJava10Compatible()) {
        it.options.release.set(targetJavaVersion)
    }
}

java {
    def javaVersion = JavaVersion.toVersion(targetJavaVersion)
    if (JavaVersion.current() < javaVersion) {
        toolchain.languageVersion = JavaLanguageVersion.of(targetJavaVersion)
    }
    withSourcesJar()
}

jar {
    from("LICENSE") {
        rename { "${it}_$archives_base_name" }
    }
}